### PR TITLE
maybe did the replacies?

### LINKED ISSUE #84: Use an env var to define the LLM to use in unit tests
cmd shift f. "mixtral" and replace by the env var

gotta change secrets in github (ping me)

### PR DESCRIPTION
**Pull request by twilwa**
hopefully fixes #84 , but my vscode isn't lighting up the env vars in blue like it normally does so i wonder if i did something wrong lol

### CODE REVIEW

**Comment by twilwa** [comment]
let env_model_name = std::env::var("ENV_MODEL_NAME").unwrap_or_else(|_| String::from("mistralai/mixtral-8x7b-instruct"));

this look right? I can add this to all the files I modified if so

**Comment by louis030195** [comment]
yeah @twilwa 

try to `cargo build` maybe or run the unit test then w the mixtral from coolrazor

**Comment by twilwa** [comment]
made some progress, but unit tests are failing -- swapped out all the ENV VAR stuff to how it's actually supposed to be in rust, but i'm getting

error[E0308]: mismatched types
    --> assistants-core/src/executor.rs:2193:27
     |
2193 |                     data: Some(serde_yaml::from_str(OPENAPI_SPEC).unwrap())})],
     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `String`, found `Option<_>`
     |
     = note: expected struct `std::string::String`
                  found enum `std::option::Option<_>`
                  
                  
error[E0282]: type annotations needed
   --> assistants-core/src/executor.rs:189:43
    |
189 |                         let data = e.data.as_ref().unwrap();
    |                                           ^^^^^^   ------ type must be known at this point
    |
help: try using a fully qualified path to specify the expected types
    |
189 |                         let data = <std::string::String as AsRef<T>>::as_ref(&e.data).unwrap();
    |                                    +++++++++++++++++++++++++++++++++++++++++++      ~
    
    
note that i don't currently have the dbs spun up or anything, those are erroring out but to be expected

env var stuff is fixed though

**Comment by louis030195** [comment]
@twilwa can you only do the changes for unit tests?

**Comment by louis030195** [comment]
ill cleanup myself

**Comment by louis030195** [comment]
@twilwa tip: usually do only one thing per pr (u did both github thiung and test env var thing)

**Pull request merged**
